<?php
// This file generated by Propel 1.3.0 convert-props target
return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'database' => 
      array (
        'classes' => 
        array (
          'ConfigurationMapBuilder' => 'orm/map/ConfigurationMapBuilder.php',
          'ConfigurationPeer' => 'orm/ConfigurationPeer.php',
          'Configuration' => 'orm/Configuration.php',
          'AdminTypeMapBuilder' => 'orm/map/AdminTypeMapBuilder.php',
          'AdminTypePeer' => 'orm/AdminTypePeer.php',
          'AdminType' => 'orm/AdminType.php',
          'AdminMapBuilder' => 'orm/map/AdminMapBuilder.php',
          'AdminPeer' => 'orm/AdminPeer.php',
          'Admin' => 'orm/Admin.php',
          'BannerMapBuilder' => 'orm/map/BannerMapBuilder.php',
          'BannerPeer' => 'orm/BannerPeer.php',
          'Banner' => 'orm/Banner.php',
          'MenuMapBuilder' => 'orm/map/MenuMapBuilder.php',
          'MenuPeer' => 'orm/MenuPeer.php',
          'Menu' => 'orm/Menu.php',
          'PageMapBuilder' => 'orm/map/PageMapBuilder.php',
          'PagePeer' => 'orm/PagePeer.php',
          'Page' => 'orm/Page.php',
          'PageTabMapBuilder' => 'orm/map/PageTabMapBuilder.php',
          'PageTabPeer' => 'orm/PageTabPeer.php',
          'PageTab' => 'orm/PageTab.php',
          'VideoSubscriberMapBuilder' => 'orm/map/VideoSubscriberMapBuilder.php',
          'VideoSubscriberPeer' => 'orm/VideoSubscriberPeer.php',
          'VideoSubscriber' => 'orm/VideoSubscriber.php',
          'VideoMapBuilder' => 'orm/map/VideoMapBuilder.php',
          'VideoPeer' => 'orm/VideoPeer.php',
          'Video' => 'orm/Video.php',
          'SubscriberMapBuilder' => 'orm/map/SubscriberMapBuilder.php',
          'SubscriberPeer' => 'orm/SubscriberPeer.php',
          'Subscriber' => 'orm/Subscriber.php',
          'NewsMapBuilder' => 'orm/map/NewsMapBuilder.php',
          'NewsPeer' => 'orm/NewsPeer.php',
          'News' => 'orm/News.php',
          'GalleryMapBuilder' => 'orm/map/GalleryMapBuilder.php',
          'GalleryPeer' => 'orm/GalleryPeer.php',
          'Gallery' => 'orm/Gallery.php',
          'GalleryPictureMapBuilder' => 'orm/map/GalleryPictureMapBuilder.php',
          'GalleryPicturePeer' => 'orm/GalleryPicturePeer.php',
          'GalleryPicture' => 'orm/GalleryPicture.php',
          'TestimonialMapBuilder' => 'orm/map/TestimonialMapBuilder.php',
          'TestimonialPeer' => 'orm/TestimonialPeer.php',
          'Testimonial' => 'orm/Testimonial.php',
          'SeoMapBuilder' => 'orm/map/SeoMapBuilder.php',
          'SeoPeer' => 'orm/SeoPeer.php',
          'Seo' => 'orm/Seo.php',
        ),
      ),
    ),
  ),
);